channels:
    - pytorch
    - conda-forge
name:
    synapse-net
dependencies:
    - cpuonly
    - bioimageio.core
    - kornia
    # This pin is necessary because later nifty versions have import errors on windows.
    - nifty =1.2.1=*_4
    - magicgui
    - napari
    - protobuf <5
    - pip
    - pyqt
    - python-elf
    - pytorch
    - torchvision
    - tensorboard
    - torch_em
    - trimesh
    - pip:
        - napari-skimage-regionprops
